"""
Generates a standalone C implementation of the per-frame statistical
compression module, given a list of feature names (subset of the
supported set below). Mirrors compress_frame_stats() in the notebook
EXACTLY so python-trained normalization stats and on-device output agree.
"""

SUPPORTED = ["mean", "std", "min", "max", "range", "rms", "skew", "kurtosis", "mad", "mean_abs_diff"]

def feature_c_snippet(f):
    # Each snippet assumes: `const float *x`, `int n`, and precomputed
    # `float mean_v, std_v, min_v, max_v;` are available in scope.
    return {
        "mean":  "out[oi++] = mean_v;",
        "std":   "out[oi++] = std_v;",
        "min":   "out[oi++] = min_v;",
        "max":   "out[oi++] = max_v;",
        "range": "out[oi++] = max_v - min_v;",
        "rms": (
            "{ float sumsq = 0.0f; for (int i = 0; i < n; i++) sumsq += x[i] * x[i]; "
            "out[oi++] = sqrtf(sumsq / (float)n); }"
        ),
        "skew": (
            "{ float s3 = 0.0f; float sd = (std_v < 1e-8f) ? 1.0f : std_v; "
            "for (int i = 0; i < n; i++) { float z = (x[i] - mean_v) / sd; s3 += z * z * z; } "
            "out[oi++] = s3 / (float)n; }"
        ),
        "kurtosis": (
            "{ float s4 = 0.0f; float sd = (std_v < 1e-8f) ? 1.0f : std_v; "
            "for (int i = 0; i < n; i++) { float z = (x[i] - mean_v) / sd; s4 += z * z * z * z; } "
            "out[oi++] = (s4 / (float)n) - 3.0f; }"
        ),
        "mad": (
            "{ float s = 0.0f; for (int i = 0; i < n; i++) s += fabsf(x[i] - mean_v); "
            "out[oi++] = s / (float)n; }"
        ),
        "mean_abs_diff": (
            "{ float s = 0.0f; for (int i = 1; i < n; i++) s += fabsf(x[i] - x[i - 1]); "
            "out[oi++] = s / (float)(n - 1); }"
        ),
    }[f]


def generate_compression_c(features, module_name, window_frames, frame_samples, n_passthrough=3):
    for f in features:
        if f not in SUPPORTED:
            raise ValueError(f"Unsupported feature '{f}'. Supported: {SUPPORTED}")

    n_compressed = len(features)
    n_out_channels = n_compressed + n_passthrough
    guard = f"{module_name.upper()}_H_"

    # ---- header ----
    header = f"""#ifndef {guard}
#define {guard}

// Auto-generated by gen_compression_c.py — DO NOT EDIT BY HAND.
// Compresses {frame_samples} raw IR sub-samples per 0.5s frame into
// {n_compressed} statistical features: [{", ".join(features)}]
// then appends {n_passthrough} passthrough channels (spo2, bpm, motion_level)
// to form one output row of {n_out_channels} channels per frame.
//
// Input window layout expected: ({window_frames}, {frame_samples + n_passthrough})
//   columns: [spo2, bpm, ir_0..ir_{frame_samples - 1}, motion_level]
// Output window layout produced: ({window_frames}, {n_out_channels})
//   columns: [{", ".join(features)}, spo2, bpm, motion_level]

#define {module_name.upper()}_WINDOW_FRAMES   {window_frames}
#define {module_name.upper()}_FRAME_SAMPLES   {frame_samples}
#define {module_name.upper()}_N_COMPRESSED    {n_compressed}
#define {module_name.upper()}_N_PASSTHROUGH   {n_passthrough}
#define {module_name.upper()}_N_OUT_CHANNELS  {n_out_channels}

// Compresses a single frame's {frame_samples} raw IR samples into
// {n_compressed} feature values, written to out[0..{n_compressed - 1}].
void {module_name}_compress_frame(const float *ir_samples, int n_samples, float *out);

// Processes one full window of raw input rows (each row:
// [spo2, bpm, ir_0..ir_{frame_samples - 1}, motion_level]) into
// {window_frames} output rows of {n_out_channels} channels each.
// in_window:  flat array, {window_frames} * {frame_samples + n_passthrough} floats, row-major
// out_window: flat array, {window_frames} * {n_out_channels} floats, row-major (caller-allocated)
void {module_name}_compress_window(const float *in_window, float *out_window);

#endif // {guard}
"""

    # ---- source ----
    lines = []
    lines.append(f'#include "{module_name}.h"')
    lines.append("#include <math.h>")
    lines.append("")
    lines.append(f"void {module_name}_compress_frame(const float *x, int n, float *out) {{")
    lines.append("    int oi = 0;")
    needs_mean = any(f in ("mean", "std", "skew", "kurtosis", "mad") for f in features)
    needs_std = any(f in ("std", "skew", "kurtosis") for f in features)
    needs_min = any(f in ("min", "range") for f in features)
    needs_max = any(f in ("max", "range") for f in features)
    if needs_mean or needs_std:
        lines.append("    float sum = 0.0f;")
        lines.append("    for (int i = 0; i < n; i++) sum += x[i];")
        lines.append("    float mean_v = sum / (float)n;")
    else:
        lines.append("    float mean_v = 0.0f; (void)mean_v;")
    if needs_std:
        lines.append("    float sumsq_dev = 0.0f;")
        lines.append("    for (int i = 0; i < n; i++) { float d = x[i] - mean_v; sumsq_dev += d * d; }")
        lines.append("    float std_v = sqrtf(sumsq_dev / (float)n);")
    else:
        lines.append("    float std_v = 0.0f; (void)std_v;")
    if needs_min:
        lines.append("    float min_v = x[0]; for (int i = 1; i < n; i++) if (x[i] < min_v) min_v = x[i];")
    else:
        lines.append("    float min_v = 0.0f; (void)min_v;")
    if needs_max:
        lines.append("    float max_v = x[0]; for (int i = 1; i < n; i++) if (x[i] > max_v) max_v = x[i];")
    else:
        lines.append("    float max_v = 0.0f; (void)max_v;")
    lines.append("")
    for f in features:
        lines.append("    " + feature_c_snippet(f))
    lines.append("}")
    lines.append("")
    lines.append(f"void {module_name}_compress_window(const float *in_window, float *out_window) {{")
    lines.append(f"    const int in_stride = {frame_samples + n_passthrough};")
    lines.append(f"    const int out_stride = {n_out_channels};")
    lines.append(f"    for (int t = 0; t < {window_frames}; t++) {{")
    lines.append("        const float *row = in_window + t * in_stride;")
    lines.append("        float spo2_v = row[0];")
    lines.append("        float bpm_v  = row[1];")
    lines.append("        const float *ir = row + 2;")
    lines.append(f"        float motion_v = row[{frame_samples + 2}];")
    lines.append("        float *out_row = out_window + t * out_stride;")
    lines.append(f"        {module_name}_compress_frame(ir, {frame_samples}, out_row);")
    lines.append(f"        out_row[{n_compressed}]     = spo2_v;")
    lines.append(f"        out_row[{n_compressed + 1}] = bpm_v;")
    lines.append(f"        out_row[{n_compressed + 2}] = motion_v;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    source = "\n".join(lines)

    return header, source